# Copyright 2018 the Deno authors. All rights reserved. MIT license.
sudo: false
language: go
git:
  depth: 1

env:
  global:
  - PATH=$HOME/.cargo/bin:$PATH
  - CARGO_HOME=$HOME/.cargo
  - RUSTUP_HOME=$HOME/.rustup
install:
- |-
  # Install Rust.
  curl -sSf https://sh.rustup.rs | sh -s -- -y
  rustc --version
  cargo --version
  rustup install nightly
- |-
  go get golang.org/dl/go1.12beta1
  go1.12beta1 download
- |-
  # Remove unnnecessary cargo and rustup directories.
  # This keeps the Travis CI cache small and fast.
  rm -rf "$RUSTUP_HOME"downloads
  rm -rf "$RUSTUP_HOME"tmp
  rm -rf "$RUSTUP_HOME"toolchains/*/etc
  rm -rf "$RUSTUP_HOME"toolchains/*/share
cache:
  directories:
    - wasabi/target
    - $HOME/.cargo/
    - "$RUSTUP_HOME"
    - $CARGO_HOME/registry/index/
    - $CARGO_HOME/registry/cache/

script:
- ./go-lib-runtime-test.sh
- cd wasabi && RUST_BACKTRACE=full cargo +nightly test --release -- --nocapture
